development:
  adapter: postgresql
  database: warstler_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: warstler_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: warstler_production
  pool: 5
  timeout: 5000
